mysite/main/urls.py
from django.urls import path
from . import views

app_name = "main"   

urlpatterns = [
  path("", views.homepage, name="homepage"),
  
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include #add include

urlpatterns = [
    path('', include('main.urls')),  #add path
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path

from . import views
"""When somebody requests a page from your website – say, “/polls/34/”, Django will load the mysite.urls Python module because it’s pointed to by the ROOT_URLCONF setting. It finds the variable named urlpatterns and traverses the patterns in order. 
After finding the match at 'polls/', it strips off the matching text ("polls/") and sends the remaining text – "34/" – to the ‘polls.urls’ URLconf for further processing. """

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/specifics/1
    path('specifics/<int:question_id>/', views.detail, name='detail'),  #views.detail makes it use the function in polls/views called detail. name='detail' can be specified in the template so as not to hardcode URLs. Very clever.
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/main/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
  name = models.CharField(max_length=100, unique=True)
  height = models.CharField(max_length=100)
  team = models.CharField(max_length=100)
  ppg = models.DecimalField(max_digits=5, decimal_places= 2)

  def __unicode__(self):
    return self.id()

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)  #true if publish date was 1 day ago or closer

class Choice(models.Model):
    referring_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    def __int__(self) -> str:
        return self.votes

mysite/main/forms.py
from django import forms
from .models import Player

class PlayerForm(forms.ModelForm):

  class Meta:
    model = Player
    fields = ('name','height','team','ppg')

mysite/main/views.py
from django.shortcuts import render
from .forms import PlayerForm
from .models import Player

# Create your views here.
def homepage(request):
  if request.method == "POST":
    form = PlayerForm(request.POST)
    if form.is_valid():
      form.save()
  players = Player.objects.all()
  form = PlayerForm()
  return render(request, "home.html", {"form": form, "players":players})

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
"""The render() function takes the request object as its first argument, 
a template name as its second argument and a dictionary as its optional third argument."""

from .models import Question, Choice
# Create your views here.

def index(request):
    """Gives a list of the last 5 questions [:5] ordered by publish date (-pub_date)"""
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # That code loads the template called polls/index.html and passes it a context. The context is a dictionary mapping template variable names to Python objects.
    return render(request, 'polls/index.html', {'latest_question_list': latest_question_list,})

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    """now draws from a html template"""
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    """updated because our template now has from element. Gets choices via POST, counts your choice as a vote and saves change to the database.
    Then returns HttpResponseRedirect to prevent data being posted twice."""
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/main/templates/home.html
<!DOCTYPE html>
<html lang="en"
<head>
    <title>Player Database</title>
</head>

<html>
   <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 
  </head>
  
  <body>
      {% load crispy_forms_tags %}

      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand mx-auto" href="">
          Player Database
        </a>
      </nav>
      <br><center><img src="https://thumbs.gfycat.com/BaggyAdorableFairybluebird-size_restricted.gif" alt="Cool Basketball Animation" style="width:180px;height:180px;">
        <img src="https://www.freepnglogos.com/uploads/nba-logo-png/nba-stats-logo-documentation-with-examples-slothparadise-11.png" alt="NBA logo" style="width:500px;height:150px;">
        <img src="https://thumbs.gfycat.com/BaggyAdorableFairybluebird-size_restricted.gif" alt="Cool Basketball Animation" style="width:180px;height:180px;"></center><br>

      <div class="container">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button class ="btn btn-primary" type="submit" id= "submit_button">Submit</button>
        <br><br><br><a href="{% url 'polls:index' %}" class="btn btn-primary">Go to Polls Page</a>
      </form>
      </div>
      <br><br>
      <div class="container">
        {% for player in players %}
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ player.name }}</h5>
            <p class="card-text">{{ player.team }}</p>
            <p class="card-text">{{ player.height }}</p>
            <p class="card-text">{{ player.ppg }}</p>
          </div>
        </div>
        {% endfor %}
      </div>

  </body>
</html>

mysite/polls/templates/polls/detail.html
<!--now this code creates a form for the choice, you can now vote your choice using radio buttons and submit it-->
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>
    <br><br><a href="{% url 'polls:index' %}" class="btn btn-primary">Go back to Polls</a>

mysite/polls/templates/polls/index.html
<!--you can refer to this template within Django as polls/index.html. This is because it knows templates will be in a folder called templates!-->
<!DOCTYPE html>
<html lang="en"
<head>
    <title>NBA Polls</title>
</head>
<a href="{% url 'main:homepage' %}" class="btn btn-primary">Go to Player Database</a>

<body>

<br><br> <font size="+2">NBA Polls:</font>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<br><br><a href="{% url 'polls:index' %}" class="btn btn-primary">Go back to Polls</a>